//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesProjectApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int itemID { get; set; }
        public int orderID { get; set; }
        public string SKU { get; set; }
        public int quantity { get; set; }
        public decimal unitPrice { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
