//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesProjectApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping_info
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string recipient_name { get; set; }
        public string phone_number { get; set; }
        public string address { get; set; }
        public string notes { get; set; }
    
        public virtual order order { get; set; }
    }
}
